/* Generated by Cython 0.29.5 */

#ifndef __PYX_HAVE__aiocouchdb__hdrs
#define __PYX_HAVE__aiocouchdb__hdrs


#ifndef __PYX_HAVE_API__aiocouchdb__hdrs

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *X_AUTH_COUCHDB_USERNAME;
__PYX_EXTERN_C PyObject *X_AUTH_COUCHDB_ROLES;
__PYX_EXTERN_C PyObject *X_AUTH_COUCHDB_TOKEN;

#endif /* !__PYX_HAVE_API__aiocouchdb__hdrs */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inithdrs(void);
#else
PyMODINIT_FUNC PyInit_hdrs(void);
#endif

#endif /* !__PYX_HAVE__aiocouchdb__hdrs */
